config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get "bienvenida", to: "home#index"
  root to: "home#index"

  resources :students

  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :user

    validates :document, :age, :number_phone, :name, :last_name, :nationality, :state, :country, :city, :address, :reason, :gender, :marital_status, :career, presence: { message: " este campo no puede estar vacio"}
    validates :date_of_birth, presence: { message: " este campo contiene datos incorrectos"}

    validates :reason, length: {minimum:30, message: " el contenido es muy corto (caracteres minimos 30)"}

    has_attached_file :photo, styles: {small: "300x400#"}
    validates_attachment_content_type :photo, content_type: /\Aimage/, message: " es invalido"
    validates_attachment_file_name :photo, matches: [/png\z/, /jpe?g\z/], message: " es invalido"
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  include PermissionsConcern
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :authenticate_student!, only: [:new]
  #before_action :authenticate_admin!, only: [:destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
    @user = User.all

  end

  # GET /students/1
  # GET /students/1.json
  def show
    #@user = User.find(params[:id])
  end

  # GET /students/new
  def new
    @student = Student.new
    @students = Student.all
    @users = User.all
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = current_user.students.create(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Registro Exitoso.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if current_user.is_admin?
        if @student.update(student_params_spcial)
          format.html { redirect_to @student, notice: 'Status de Beca Establecida con Exito.' }
          format.json { render :show, status: :ok, location: @student }
        else
          format.html { render :edit }
          format.json { render json: @student.errors, status: :unprocessable_entity }
        end
      else
        if @student.update(student_params)
          format.html { redirect_to @student, notice: 'Actualizacion Exitosa.' }
          format.json { render :show, status: :ok, location: @student }
        else
          format.html { render :edit }
          format.json { render json: @student.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
=begin
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Registro eliminado con exito.' }
      format.json { head :no_content }
    end
  end
=end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
        @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:document, :name, :last_name, :age, :date_of_birth, :email, :gender, :marital_status, :nationality, :number_phone, :country, :state, :city, :address, :career, :reason,:photo)
    end

    def student_params_spcial
      params.require(:student).permit(:scholarship_status)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true, class:"was-validated text-uppercase") do |f| %>

<% if current_user.is_admin? == false%>
<% if student.errors.any? %>
<div class="mt-3 mb-3 border-error alert-danger text-justify">

    <div id="error_explanation" class="p-3">
        <% if student.errors.count == 1%>
        <h4 class="alert-heading mb-2"><%= pluralize(student.errors.count, "error ")%>ha impedido que los datos se guardaran, verifique el siguiente campo:</h4>
        <% else %>
        <h4 class="alert-heading mb-2"><%= pluralize(student.errors.count, "errores")%> han impedido que los datos se guardaran, verifique los siguientes campos:</h4>
        <%end%>
        <ul>
            <% student.errors.full_messages.each do |message| %>
            <li>* <%= message %>.</li>
            <% end %>
        </ul>
    </div>

</div>
<% end %>

<div class="mb-3">
    <label for="validationInput1">dni</label>
    <input class="form-control is-invalid" id="validationInput1" placeholder="INGRESE SU NUMERO DE IDENTIFICACION NACIONAL" type="text" onkeypress="return soloNumeros(event)" value="<%= @student.document %>" name="student[document]" required></input>
</div>

<div class="mb-3">
    <label for="validationInput">nombre(s)</label>
    <input class="form-control is-invalid text-uppercase" id="validationInput" placeholder="Ingrese su nombre completo" name="student[name]" value="<%= @student.name %>" type="text" onkeypress="return soloLetras(event)" required></input>
</div>

<div class="mb-3">
    <label for="validationInput">apellido(s)</label>
    <input class="form-control is-invalid text-uppercase" id="validationInput" placeholder="Ingrese su apellido completo" name="student[last_name]" value="<%= @student.last_name %>" type="text" onkeypress="return soloLetras(event)" required></input>
</div>


<div class="mb-3">
    <label for="validationInput">fecha de nacimiento</label>
    <input type="date" class="form-control is-invalid" id="validationInput" name="student[date_of_birth]" value="<%= student.date_of_birth %>" required>
</div>

<div class="mb-3">
    <label>correo electronico</label>
    <input class="form-control is-valid" placeholder="Ingrese su correo electronico" name="student[email]" value="<%= current_user.email.upcase %>" type="email" readonly></input>
</div>

<div class="mb-3">
    <label for="validationInput">edad</label>
    <input class="form-control is-invalid" id="validationInput" placeholder="INGRESE SU EDAD" type="number" onkeypress="return soloNumeros(event)" name="student[age]" value="<%= @student.age %>" required></input>
</div>

<div>
    <label>sexo</label>
    <div class="custom-control custom-radio">
        <input type="radio" class="custom-control-input text-uppercase" id="customControlValidation2" name="student[gender]" value="femenino" required <%if student.gender === 'femenino' %> checked <% end %>>
        <label class="custom-control-label" for="customControlValidation2">femenino</label>
    </div>
    <div class="custom-control custom-radio mb-3">
        <input type="radio" class="custom-control-input" id="customControlValidation3" name="student[gender]" value="masculino" required <%if student.gender === 'masculino' %> checked <% end %>>
        <label class="custom-control-label" for="customControlValidation3">masculino</label>
        <div class="invalid-feedback">Seleccione una opcion</div>
    </div>
</div>

<div class="form-group">
    <label>estado civil</label>
    <select class="custom-select" name="student[marital_status]" onChange="validar(this,1)" onBlur="validar(this,1)" required>
        <option value="">--SELECCIONA UNA OPCION--</option>
        <option value="soltero" <%if student.marital_status === 'soltero' %> selected="selected" <%end%>>SOLTERO</option>
        <option value="casado" <%if student.marital_status === 'casado' %>selected="selected" <%end%>>CASADO</option>
        <option value="divorciado" <%if student.marital_status === 'divorciado' %> selected="selected" <%end%>>DIVORCIADO</option>
    </select>
    <div class="invalid-feedback">Seleccione una opcion valida</div>
</div>

<div class="mb-3">
    <label for="validationInput">nacionalidad</label>
    <input class="form-control is-invalid text-uppercase" id="validationInput" placeholder="Ingrese su nacionalidad" name="student[nationality]" value="<%= @student.nationality %>" type="text" onkeypress="return soloLetras(event)" required="required"></input>
</div>

<div class="mb-3">
    <label for="validationInput">numero de telefono</label>
    <input class="form-control is-invalid" id="validationInput" placeholder="INGRESE SU NUMERO DE TELEFONO" type="number" onkeypress="return soloNumeros(event)" name="student[number_phone]" value="<%= @student.number_phone %>" required="required"></input>
</div>

<div class="mb-3">
    <label for="validationInput">pais</label>
    <input class="form-control is-invalid text-uppercase" id="validationInput" placeholder="Ingrese su pais" name="student[country]" value="<%= @student.country %>" type="text" onkeypress="return soloLetras(event)" required></input>
</div>

<div class="mb-3">
    <label for="validationInput">estado</label>
    <input class="form-control is-invalid text-uppercase" id="validationInput" placeholder="Ingrese su estado" name="student[state]" value="<%= @student.state %>" type="text" onkeypress="return soloLetras(event)" required></input>
</div>

<div class="mb-3">
    <label for="validationInput">ciudad</label>
    <input class="form-control is-invalid text-uppercase" id="validationInput" placeholder="Ingrese su ciudad" name="student[city]" value="<%= @student.city %>" type="text" onkeypress="return soloLetras(event)" required></input>
</div>

<div class="mb-3">
    <label for="validationInput">direccion</label>
    <input class="form-control is-invalid text-uppercase" id="validationInput" placeholder="Ingrese su direccion" name="student[address]" value="<%= @student.address %>" type="text" required></input>
</div>

<div class="form-group">
    <label>carreras disponibles</label>
    <select class="custom-select" name="student[career]" onChange="validar(this,2)" onBlur="validar(this,2)" required>
        <option value="">--SELECCIONA UNA OPCION--</option>
        <option value="informatica" <%if student.career === 'informatica' %> selected="selected" <%end%>>INFORMATICA</option>
        <option value="derecho" <%if student.career === 'derecho' %>selected="selected" <%end%>>DERECHO</option>
        <option value="administracion" <%if student.career === 'administracion' %> selected="selected" <%end%>>ADMINISTRACION</option>
        <option value="telecomunicaciones" <%if student.career === 'telecomunicaciones' %> selected="selected" <%end%>>TELECOMUNICACIONES</option>
    </select>
    <div class="invalid-feedback">Seleccione una opcion valida</div>
</div>

<div class="mb-3">
    <label class="text-justify" for="validationTextarea">Razon por la que considera que merece la beca</label>
    <textarea rows="10" minlength="30" class="form-control is-invalid text-uppercase altura" id="validationTextarea" placeholder="Debe ingresar un contenido min. 30 caracteres" name="student[reason]" value="<%= student.reason %>" required><%= @student.reason%></textarea>
</div>

<p>foto de perfil</p>
<% if @student.photo.file? %>
<button class="btn btn-success d-block" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">CAMBIAR FOTO DE PERFIL</button>
<div class="collapse" id="collapseExample">
    <div class="custom-file mt-2">
        <%= f.file_field :photo, class:"custom-file-input is-invalid", id:"validatedCustomFile"%>
        <label class="custom-file-label" for="validatedCustomFile">Sube una foto...</label>
        <div class="invalid-feedback">Debe subir un archivo valido. formatos permitidos (jpg, jpeg, png).</div>
    </div>
</div>
<%else%>
<div class="custom-file mt-2">
    <%= f.file_field :photo, class:"custom-file-input", id:"validatedCustomFile", required:"required"%>
    <label class="custom-file-label" for="validatedCustomFile">Sube una foto...</label>
    <div class="invalid-feedback">Debe subir un archivo valido. formatos permitidos (jpg, jpeg, png).</div>
</div>
<%end%>
<%else%>  <!-- ESTATUS DE LA BECA -->
<div class="">
    <label class="font-weight-bold text-success">estatus de la beca excelencia</label>
    <div class="custom-control custom-radio">
        <input type="radio" class="custom-control-input text-uppercase" id="customControlValidation2" name="student[scholarship_status]" value="en_espera" required <%if student.scholarship_status === 'en_espera' %> checked <% end %>>
        <label class="custom-control-label" for="customControlValidation2">en espera</label>
    </div>
    <div class="custom-control custom-radio">
        <input type="radio" class="custom-control-input text-uppercase" id="customControlValidation3" name="student[scholarship_status]" value="aprobada" required <%if student.scholarship_status === 'aprobada' %> checked <% end %>>
        <label class="custom-control-label" for="customControlValidation3">Aprobar</label>
    </div>
    <div class="custom-control custom-radio mb-3">
        <input type="radio" class="custom-control-input" id="customControlValidation4" name="student[scholarship_status]" value="rechazada" required <%if student.scholarship_status === 'rechazada' %> checked <% end %>>
        <label class="custom-control-label" for="customControlValidation4">rechazar</label>
        <div class="invalid-feedback">Seleccione una opcion</div>
    </div>
</div>
<%end%>
<!--FINAL DE LA CONDICION -->

<div class="actions mt-5">
    <%= f.submit "GUARDAR", class:"btn btn-primary" %>
    <%= link_to 'VOLVER', @student, class:"btn btn-primary float-right" %>
</div>
<% end %>
<!--FINAL DEL CICLO FOR -->

app/views/students/edit.html.erb
<% if current_user.id == @student.user_id || current_user.is_admin?%>
<div class="container margin-top">
    <div class="m-5 bg-nav px-5 py-4 borde">
        <%unless current_user.is_admin?%>
        <h1 class="text-primary text-center mb-5">EDITAR FICHA</h1>
        <%else%>
        <h1 class="text-primary text-center mb-5">PROCESAR SOLICITUD DE BECA</h1>
        <%end%>
        <%= render 'form', student: @student %>

    </div>
</div>
<%else%>
<div class="container margin-top">
    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Ooooopss!!!</h4>
        <p class="text-uppercase">Parece que la Url tiene un error, pulsa el boton volver para ir a una url valida.</p>
        <p class="mb-0"><%= link_to 'VOLVER', students_path, class:"btn btn-danger mt-2" %></p>
    </div>
</div>
<%end%>

app/views/students/index.html.erb
<div class="container margin-top">
    <div class="m-5 bg-nav px-5 py-4 borde">
        <% if current_user.is_admin? %>
        <h2 class="text-center text-info mb-5">Lista de Solicitudes</h2>
        <% end %>

        <% status_std = false %>

        <% @students.each do |student| %>
        <% if current_user.id == student.user_id || current_user.is_admin?%>

        <div clas="row ">

            <div class="border-bottom text-uppercase mb-3 pb-3">
                <div class="col-xl-3">
                    <div class="avatar">
                        <%= image_tag student.photo.url(), alt:"foto" %>
                    </div>
                </div>
                <div class="col-xl-9 height">
                    <p><strong>NOMBRE: </strong><%= student.name %> <%= student.last_name %></p>
                    <p><strong>CARRERA: </strong><%= student.career.upcase %></p>

                    <%= link_to 'VER', student, class:"btn btn-primary mr-4" %>
                    <% unless current_user.is_admin?%>
                    <%= link_to 'EDITAR', edit_student_path(student), class:"btn btn-primary mr-3" %>

                    <% else %>
                    <!--
                    <%= link_to 'eliminar', student, method: :delete, data: { confirm: 'Esta seguro de eliminar este registro?' }, class:"btn btn-danger mr-3" %>
                    -->
                    <%if student.scholarship_status === "en_espera"%>
                    <button class="btn btn-secondary text-uppercase desactivado" disabled>Solicitud en espera</button>
                    <%elsif student.scholarship_status === "aprobada"%>
                    <button class="btn btn-success text-uppercase desactivado" disabled>Solicitud aprobada</button>
                    <%else%>
                    <button class="btn btn-danger text-uppercase desactivado" disabled>Solicitud rechazada</button>
                    <%end%>
                    <%end%>
                </div>
                <% status_std = true %>

            </div>
        </div>
        <% end %>
        <% end %>

        <% if status_std != true && current_user.is_admin? != true%>
        <p class="text-center">
        <%= link_to 'llenar ficha de datos', new_student_path, class:"btn btn-success align-center text-uppercase" %></p>
        <% end %>
    </div>
</div>

app/views/students/new.html.erb
<% usuario_registro = false%>
<% @students.each do |student|%>
    <%if student.user_id === current_user.id%>
        <%usuario_registro = true%>
    <%end%>
<%end%>

<%if usuario_registro === false%>
<div class="container margin-top">
    <div class="m-5 bg-nav px-5 py-4 borde">
        <h1 class="text-primary text-uppercase text-center mb-5">nueva ficha de datos</h1>

        <%= render 'form', student: @student %>

    </div>
</div>
<%else%>
<div class="container margin-top">
    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Ooooopss!!!</h4>
        <p class="text-uppercase">Parece que la Url tiene un error, pulsa el boton volver para ir a una url valida.</p>
        <p class="mb-0"><%= link_to 'VOLVER', students_path, class:"btn btn-danger mt-2" %></p>
    </div>
</div>
<%end%>

app/views/students/show.html.erb
<% if current_user.id === @student.user_id || current_user.is_admin? || @student.user_id === 1%>

<div class="container margin-top">
    <div class="m-5 bg-nav px-5 py-4 borde text-uppercase">

        <h2 class="text-center font-weight-bold text-info"><%= @student.name %> <%= @student.last_name%></h2>
        <div class="mt-5">
            <div class="tamaño mb-3">
                <%= image_tag @student.photo.url() %>
            </div>
            <p><strong>DNI: </strong><%= @student.document %></p>

            <p><strong>nacionalidad: </strong><%= @student.nationality %></p>

            <p><strong>fecha de nacimiento: </strong><%= @student.date_of_birth %></p>

            <p><strong>edad: </strong><%= @student.age %></p>

            <p><strong>genero: </strong><%= @student.gender.upcase %></p>

            <p><strong>estado civil: </strong><%= @student.marital_status.upcase %></p>

            <p><strong>numero de telefono: </strong><%= @student.number_phone %></p>

            <p><strong>correo electronico: </strong><%= @student.email %></p>

        </div>

        <div class="sda-seccion">
            <div class="bg-info border-subt">
                <h2 class="font-italic font-weight-bold p-2 text-white">ubicacion</h2>
            </div>
            <p><strong>pais: </strong><%= @student.country %></p>

            <p><strong>estado: </strong><%= @student.state %></p>

            <p><strong>ciudad: </strong><%= @student.city %></p>

            <p><strong>direccion: </strong><%= @student.address %></p>
        </div>
        <div class="sda-seccion my-3">
            <div class="bg-info border-subt">
                <h2 class="font-italic font-weight-bold p-2 text-white">postulacion</h2>
            </div>
            <p><strong>carrera: </strong><%= @student.career.upcase %></p>

            <p><strong>Razon por la que considera que merece la beca: </strong><%= @student.reason %></p>
        </div>

        <% if current_user.is_admin?%>

        <%if @student.scholarship_status == "en_espera"%>
        <%= link_to 'procesar solicitud de beca', edit_student_path(@student), class:"btn btn-warning btn-lg mt-3 border text-white font-weight-bold btn-block" %>

        <%elsif @student.scholarship_status == "aprobada"%>

        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Beca Aceptada!</h4>
            <p>Esta beca ha sido aceptada por el administrador. Aparecera en la ficha de datos del estudiante un mensaje de que ha sido aprobada la solicitud de la <strong>beca excelencia</strong>.</p>
            <hr>
            <p class="mb-0">si desea cambiar el status de la beca del estudiante presione el boton a continacion <%= link_to 'cambiar status', edit_student_path(@student), class:"btn btn-success mt-2" %></p>
        </div>

        <%else%>
        <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">Beca Rechazada!</h4>
            <p>Esta beca ha sido rechazada por el administrador. Aparecera en la ficha de datos del estudiante un mensaje de que ha sido rechazada la solicitud de la <strong>beca excelencia</strong>.</p>
            <hr>
            <p class="mb-0">si desea cambiar el status de la beca del estudiante presione el boton a continacion <%= link_to 'cambiar status', edit_student_path(@student), class:"btn btn-danger mt-2" %></p>
        </div>
        <%end%>

        <%else%>
        <!-- VISTA DEL USUARIO-->

        <%if @student.scholarship_status == "en_espera"%>

        <div class="alert alert-dark" role="alert">
            <h4 class="alert-heading font-weight-bold">En Espera!!!</h4>
            <p class="text-justify">Sus datos han sido cargados con exito. la solicitud sera procesada en un lapso no mayor a 05 (cinco) dias; dicho procesamiento sera reflejado en esta seccion, le aconsejamos que revice la pagina constantemente para verificar el status de la solicitud de su beca. gracias por postularse!!!.</p>
            <hr>

        </div>

        <%elsif @student.scholarship_status == "aprobada"%>

        <div class="alert alert-success" role="alert">
            <h2 class="alert-heading font-weight-bold">Felicidades!!!</h2>
            <p class="text-justify">La <strong>Beca excelencia</strong> le ha sido aprobada. para proceder con su inscripcion en la universidad debe presentarse en la misma cuando le sea notificado via telefonica y por correo electronico. esperamos que pueda valorar esta oportunidad y su desempeño pueda ser excepcional en esta casa de estudio.</p>
            <hr>
        </div>

        <%else%>

        <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading font-wight-bold">Beca Rechazada!!!</h4>
            <p class="text-justify">la <strong>beca excelencia</strong> le ha sido rechazada. gracias por postularse y le instamos a seguir esforzandose por obtener una capacitacion universitaria, esto no debe ser motivo para que se rinda. la vida es un constante aprendizaje y la educacion es una parte esencial de nuestro diario vivir. Es la educacion lo que determina el futuro.</p>
            <hr>
        </div>
        <%end%>

        <%end%>

        <div class="mt-5">
            <% unless current_user.is_admin?%>
            <%= link_to 'editar', edit_student_path(@student), class:"btn btn-primary float-right" %>
            <%end%>
            <%= link_to 'volver', students_path, class:"btn btn-primary" %>
        </div>
    </div>
</div>

<%else%>

<div class="container margin-top">
    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Ooooopss!!!</h4>
        <p class="text-uppercase">Parece que la Url tiene un error, pulsa el boton volver para ir a una url valida.</p>
        <p class="mb-0"><%= link_to 'VOLVER', students_path, class:"btn btn-danger mt-2" %></p>
    </div>
</div>
<%end%>